# -*- coding: utf-8 -*-
"""stock code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqhF1o2-gvOamyyCb7LKmA0_T94lnhnI
"""

import pandas as pd

import pandas as pd
data=pd.read_csv("/content/tesla-stock-price.csv")

data.head()

data.columns=["date","high","low","open","close","volume"]
data.head()



X = data[['close','open','high']] #input
y=data[['volume'] ]

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)



from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(X,y)

from sklearn import metrics

from sklearn.metrics import r2_score

lr.fit(X,y)

y_pred = lr.predict(X)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

mean_absolute_error(y,y_pred)

mean_squared_error(y,y_pred)

r2_score(y,y_pred)